export const categories = [
  "A-1-1 Whole Milk",
  "A-1-2 Reduced Fat Milk (2%)",
  "A-1-3 Lowfat Milk (1%)",
  "A-1-4 Nonfat Milk (Skim)",
  "A-1-5 Flavored Milk (Chocolate, Strawberry, etc.)",
  "A-1-6 Powdered Milks",
  "A-1-7 Condensed Milks",
  "A-1-O Other Dairy Milk",
  "A-2-1 Hard Cheese (Cheddar, Parmesan, etc.)",
  "A-2-2 Soft Cheese (Mozzarella, Brie, etc.)",
  "A-2-3 Cottage/Ricotta Cheese",
  "A-2-O Other Cheese",
  "A-3-1 Regular Yogurt",
  "A-3-2 Greek Yogurt",
  "A-3-3 Strawberry Yogurt",
  "A-3-4 Vanilla Yogurt",
  "A-3-O Other Yogurt",
  "A-4-1 Milk Shakes",
  "A-4-2 Sorbet",
  "A-4-3 Butter",
  "A-4-4 Ice Cream",
  "A-4-5 Kefir",
  "A-4-6 Whey based protein powders",
  "A-4-O Other Dairy Products (unspecified)",
  "A-5-1 Plant-Based Cheese",
  "A-5-2 Plant-Based Yogurt",
  "A-5-O Other Dairy alternatives (excluding beverages which are found in H-5)",
  "B-1-1 Yeast Breads (Loaves)",
  "B-1-2 Rolls & Buns",
  "B-1-3 Bagels",
  "B-1-4 Tortillas",
  "B-2-1 Biscuits",
  "B-2-2 Muffins",
  "B-2-3 Pancakes",
  "B-2-4 Waffles",
  "B-2-5 English muffins",
  "B-3-1 Ready-to-Eat Cereal (High Sugar)",
  "B-3-2 Ready-to-Eat Cereal (Low Sugar)",
  "B-3-3 Dry oats",
  "B-3-4 Cooked Oats",
  "B-3-5 Grits",
  "B-4-1 Rice (White, Brown, etc.)",
  "B-4-2 Pasta",
  "B-4-3 Noodles",
  "B-4-4 Fried Rice",
  "B-4-5 Rice baked products",
  "B-5-1 Bulgur",
  "B-5-2 Quinoa",
  "B-5-3 Farro",
  "B-5-4 Millet",
  "B-5-O Other Grain Products",
  "B-6-1 Croissants",
  "B-6-2 Danishes",
  "B-6-O Other Pastries",
  "C-1-1 Chia seeds",
  "C-1-2 Flaxseeds",
  "C-1-3 Pumpkin Seeds",
  "C-1-4 Sesame Seeds",
  "C-1-O Other seeds",
  "C-2-1 Almonds",
  "C-2-2 Peanuts",
  "C-2-3 Walnuts",
  "C-2-4 Pecan Nuts",
  "C-2-5 Hazelnuts",
  "C-2-6 Brazil Nuts",
  "C-2-7 Macadamia Nuts",
  "C-2-8 Pistachio",
  "C-2-9 Cashew",
  "C-2-10 Mixed Nuts",
  "C-2-O Other Nuts",
  "D-1-1 Beef (Excluding Ground)",
  "D-1-2 Ground Beef",
  "D-1-3 Lamb, Goat, Game",
  "D-1-4 Poultry (Chicken, Turkey, Duck)",
  "D-1-5 Sausages",
  "D-1-6 Organ meats",
  "D-1-7 Pork",
  "D-1-O Other meats",
  "D-2-1 Dried Meat (Jerky)",
  "D-2-2 Bacon",
  "D-2-3 Sausages",
  "D-2-O Other cured meats",
  "D-3-1 Fish",
  "D-3-2 Salmon",
  "D-3-3 Tuna",
  "D-3-4 Shrimp",
  "D-3-5 Crab",
  "D-3-6 Lobster",
  "D-3-7 Octopus",
  "D-3-8 Clams",
  "D-3-9 Mussels",
  "D-3-10 Sardines",
  "D-3-11 Squid",
  "D-3-12 Scallops",
  "D-3-13 Mackerel",
  "D-3-O Other seafood",
  "D-4-1 Eggs",
  "D-4-2 Fried Eggs",
  "D-4-3 Tea Eggs",
  "D-4-4 Egg whites",
  "D-4-5 Egg yolks",
  "D-5-1 Vegetable based protein",
  "D-5-2 Nuts",
  "D-5-3 Processed Nut Products (excluding nut butters)",
  "D-5-4 Processed Soy Products (Tofu, Tempeh)",
  "D-5-5 Plant based meat alternatives",
  "D-6-1 Protein Powders (excluding whey based)",
  "D-6-2 Protein Drinks",
  "D-6-3 Protein Bars",
  "D-6-4 Insect based protein",
  "D-6-O Other Protein Sources",
  "E-1-1 Strawberries",
  "E-1-2 Blueberries",
  "E-1-3 Blackberries",
  "E-1-4 Raspberries",
  "E-1-5 Cranberries",
  "E-1-6 Goji Berries",
  "E-1-7 Acai Berries",
  "E-1-8 Mixed Berries",
  "E-1-O Other Berries",
  "E-2-1 Oranges",
  "E-2-2 Grapefruit",
  "E-2-3 Tangerines and Mandarins",
  "E-2-4 Lemons & Limes",
  "E-2-O Other Citrus",
  "E-3-1 Watermelon",
  "E-3-2 Cantaloupe",
  "E-3-3 Honeydew",
  "E-3-O Other melons",
  "E-4-1 Peaches",
  "E-4-2 Nectarines",
  "E-4-3 Plums",
  "E-4-4 Cherries",
  "E-4-5 Apricots",
  "E-4-6 Lychees",
  "E-4-O Other Stone Fruit",
  "E-5-1 Mango",
  "E-5-2 Banana",
  "E-5-3 Pineapple",
  "E-5-4 Dragon Fruit",
  "E-5-5 Durian Fruit",
  "E-5-6 Jackfruit",
  "E-5-7 Kiwi",
  "E-5-8 Avocado",
  "E-5-9 Papaya",
  "E-5-10 Coconut",
  "E-5-O Other tropical fruit",
  "E-6-1 Apples",
  "E-6-2 Pears",
  "E-6-3 Grapes",
  "E-6-4 Olives",
  "E-6-5 Figs",
  "E-6-6 Dried Fruits",
  "E-6-7 Dates",
  "E-6-8 Mixed Fruit",
  "E-6-9 Pomegrenate",
  "E-6-10 Guava",
  "E-6-O Other Fruits",
  "F-1-1 Spinach",
  "F-1-2 Kale",
  "F-1-3 Lettuce (e.g. for salads)",
  "F-1-4 Bok Choy",
  "F-1-O Other Green Leafy Vegetables",
  "F-2-1 Broccoli",
  "F-2-2 Cauliflower",
  "F-2-3 Cabbage",
  "F-2-O Other Cruciferous Vegetables",
  "F-3-1 Squash",
  "F-3-2 Zucchini",
  "F-3-3 Pumpkin",
  "F-4-1 Potatoes",
  "F-4-2 Corn",
  "F-4-3 Sweet Potatoes",
  "F-4-4 Mashed Potatoes",
  "F-4-5 Yam",
  "F-4-O Other Starchy Vegetables",
  "F-5-1 Beets",
  "F-5-2 Carrots",
  "F-5-3 Turnips",
  "F-5-4 Ginger (fresh)",
  "F-5-5 Radish",
  "F-5-6 Parsnips",
  "F-5-O Other Root Vegetables",
  "F-6-1 Lentils",
  "F-6-2 Chickpeas",
  "F-6-3 Soybeans",
  "F-6-4 Green peas",
  "F-6-5 Beans (Black beans, Kidney beans)",
  "F-7-1 Kelp",
  "F-7-2 Seaweed",
  "F-7-O Other Sea Vegetables",
  "F-8-1 Onions",
  "F-8-2 Garlic",
  "F-8-3 Celery",
  "F-8-3 Tomatoes",
  "F-8-4 Eggplant",
  "F-8-5 Peppers",
  "F-8-6 Mushrooms (e.g. shiitake, oyster, cremini, truffle etc.)",
  "F-8-7 Cucumber",
  "F-8-8 Green beans",
  "F-8-9 Artichokes",
  "F-8-10 Asparagus",
  "F-8-O Other Vegetables",
  "G-1-1 Chips (Potato, Corn, etc.)",
  "G-1-2 Pretzels",
  "G-1-3 Popcorn",
  "G-1-4 Crackers",
  "G-1-O Other Salty Snacks",
  "G-2-1 Cereal Bars",
  "G-2-2 Nutrition Bars",
  "G-2-3 Dark chocolate",
  "G-2-4 White chocolate",
  "G-2-5 Caramel",
  "G-2-6 Candy (Chocolate)",
  "G-2-7 Candy (Non-Chocolate)",
  "G-2-8 Gummy sweets (bear shaped)",
  "G-2-9 Gummy sweets (worm shaped)",
  "G-2-10 Gummy sweets (other shape)",
  "G-2-11 Licorice",
  "G-2-12 Marshmallow",
  "G-2-13 Hard candy",
  "G-2-14 Cotton Candy",
  "G-2-O Other Sweet Snacks",
  "G-3-1 Cakes",
  "G-3-2 Sweet Pies (e.g. apple/fruit pie or crumble)",
  "G-3-3 Cookies",
  "G-3-4 Macarons",
  "G-3-5 Doughnuts",
  "G-3-6 Brownies",
  "G-3-7 Desserts",
  "G-3-8 Fruit Sorbets",
  "G-3-9 Gelatin based dessert",
  "G-3-10 Frozen Desserts (Excluding Ice Cream)",
  "G-3-11 Pudding",
  "G-3-O Other Desserts",
  "H-1-1 Tap Water",
  "H-1-2 Bottled Water",
  "H-1-3 Flavored Sparkling Water",
  "H-1-4 Flavored/Enhanced Water",
  "H-2-1 Citrus Juice",
  "H-2-2 Apple juice",
  "H-2-3 Vegetable Juice",
  "H-2-4 Pineapple Juice",
  "H-2-O Other Fruit Juice",
  "H-3-1 Soft Drinks",
  "H-3-2 Fruit Drinks",
  "H-3-3 Energy Drinks",
  "H-4-1 All Diet Drinks",
  "H-5-1 Oat milk",
  "H-5-2 Soy Milk",
  "H-5-3 Almond Milk",
  "H-5-4 Cashew Milk",
  "H-5-5 Macadamia Milk",
  "H-5-O Other Dairy Drink Alternatives",
  "H-6-1 Plain coffee",
  "H-6-2 Coffee with milk or cream (e.g. latte)",
  "H-7-1 Green Tea",
  "H-7-2 Black Tea",
  "H-7-3 White Tea",
  "H-7-4 Herbal Tea",
  "H-7-5 Oolong Tea",
  "H-7-6 Tea with milk or cream (e.g. chai)",
  "H-7-O Other Tea",
  "H-8-1 Caffeinated Drinks",
  "H-8-2 Electrolyte Drinks",
  "H-8-O Other energy drinks",
  "H-9-1 Wine",
  "H-9-2 Beer",
  "H-9-3 Cider",
  "H-9-4 Spirits",
  "H-9-5 Premixed alcoholic beverages",
  "H-9-O Other alcoholic beverages",
  "H-10-1 Fruit Smoothies",
  "H-10-2 Green Smoothies",
  "H-10-3 Protein Smoothies",
  "H-10-4 Dairy-Based Smoothies",
  "H-10-5 Non-Dairy Smoothies",
  "H-10-O Other Smoothies",
  "I-1-1 Lard",
  "I-2-1 Olive Oil",
  "I-2-2 Canola Oil",
  "I-2-3 Coconut Oil",
  "I-2-O Other Vegetable Oils",
  "I-3-1 Margarine",
  "I-4-1 Creams",
  "I-4-O Other Creams & Spreads",
  "J-1-1 Tomato-based (Ketchup, Marinara, Salsa)",
  "J-1-2 Mustard-Based",
  "J-1-3 Soy-Based (Soy Sauce, Teriyaki)",
  "J-1-4 Vinegars (Balsamic, Rice Wine)",
  "J-1-5 Hot Sauces",
  "J-1-6 Salad Dressings",
  "J-1-7 Dips & Spreads (Hummus, Relish)",
  "J-1-8 Gravies",
  "J-1-9 BBQ Sauce",
  "J-1-10 Mayonnaise",
  "J-1-11 Guacamole",
  "J-1-12 Pesto",
  "J-1-13 Sesame based condiments",
  "J-1-O Other Salty Condiments",
  "J-2-1 Chocolate spreads",
  "J-2-2 Marmelade",
  "J-2-3 Strawberry Jelly",
  "J-2-4 Honey",
  "J-2-5 Peanut Butter",
  "J-2-6 Almond butter",
  "J-2-7 Alternative Nut Butters",
  "J-2-8 Fruit Jelly",
  "J-2-O Other Spreads",
  "J-3-1 Maple Syrup",
  "J-3-O Other Syrups",
  "K-1-1 Tacos",
  "K-1-2 Burritos",
  "K-1-3 Pasta",
  "K-1-4 Pizza",
  "K-1-5 Stir Fry",
  "K-1-6 Miso Soup",
  "K-1-7 Poke Bowl",
  "K-1-8 Dumplings",
  "K-1-9 Maki",
  "K-1-10 Sushi",
  "K-1-11 Noodle based dishes",
  "K-1-12 Sandwiches",
  "K-1-13 Soups and Stews",
  "K-1-14 Casseroles",
  "K-1-15 Salads (substantial mixed salads as main dishes)",
  "K-1-16 Curry dishes",
  "K-1-O Other Specialty Cuisine",
  "K-2-1 Meat-Based Mixed Dishes",
  "K-2-2 Poultry-Based Mixed Dishes",
  "K-2-3 Seafood-Based Mixed Dishes",
  "K-2-4 Vegetarian Mixed Dishes",
  "K-3-1 Savoury Pie",
  "K-3-O Other Savoury Pies",
  "K-4-1 Burger",
  "K-4-2 Fries",
  "K-4-3 Fried Chicken",
  "K-4-4 Kebab",
  "K-5-1 Sauerkraut",
  "K-5-2 Kimchi",
  "K-5-3 Pickled Vegetables",
  "K-5-4 Pickled Ginger",
  "K-5-O Other Fermented Dishes",
  "K-6-1 Processed Vegetables",
  "K-6-2 Processed Meats",
  "K-6-3 Processed Fruits",
  "K-6-4 Processed Fish",
  "K-6-O Other Processed Foods",
  "K-7-1 Instant Noodles",
  "K-7-O Other Packaged Foods",
  "L-1-1 Purees (single fruit or vegetable)",
  "L-1-2 Combinations (fruits/vegetables, or with grains)",
  "L-1-3 Textured Foods (chunkier textures)",
  "L-1-4 Finger Foods & Snacks (puffs, teething biscuits)",
  "L-1-5 Yogurt & Dairy Products",
  "L-1-6 Infant Cereal",
  "L-2-1 Ready-to-Feed",
  "L-2-2 Powdered (to be mixed with water)",
  "L-2-3 Concentrate (to be diluted with water)",
  "L-2-4 Specialty Formulas (soy-based, hypoallergenic, etc.)",
  "M-1-1 Specialty products, unique ethnic foods, etc.",
  "M-1-2 Meal replacements shakes",
  "M-1-3 Meal replacements bars",
  "M-2-1 Vitamins",
  "M-2-2 Gel based supplements (e.g. energy gels)",
  "M-2-3 Gummy based supplements",
  "M-2-4 Powdered supplements",
  "M-2-O Other supplements",
  "M-3-1 Stevia",
  "M-3-2 Coconut Sugar",
  "M-3-O Other Sweeteners",
  "M-4-1 Yeast",
  "M-4-2 Baking Powder",
  "M-4-3 Baking Soda",
  "M-4-O Other Leavening Agents",
  "N-1-1 Basil",
  "N-1-2 Cilantro (Coriander leaves)",
  "N-1-3 Parsley",
  "N-1-4 Mint",
  "N-1-5 Dill",
  "N-1-6 Thyme",
  "N-1-7 Rosemary",
  "N-1-8 Sage",
  "N-1-O Other Fresh Herbs",
  "N-2-1 Dried Basil",
  "N-2-2 Dried Oregano",
  "N-2-3 Dried Thyme",
  "N-2-4 Dried Rosemary",
  "N-2-5 Dried Bay Leaves",
  "N-2-O Other Dried Herbs",
  "N-3-1 Black Pepper",
  "N-3-2 Cinnamon",
  "N-3-3 Cumin",
  "N-3-4 Nutmeg",
  "N-3-5 Paprika",
  "N-3-6 Turmeric",
  "N-3-7 Ginger (Dried)",
  "N-3-8 Cloves",
  "N-3-9 Saffron",
  "N-3-O Other Spices"
]
