const {test}=require('node:test');
const assert=require('node:assert/strict');
const {Client}=require('pg');
const {assertDisposable}=require('./helpers/mealTestDb.cjs');
const {read,prepare}=require('./helpers/userFoodsDb.cjs');

// People and sharing (20261015020000) on a disposable local Postgres, over the custom foods fixture.
const connectionString=process.env.AMINO_USER_FOODS_TEST_DATABASE_URL;
const alice='00000000-0000-4000-8000-00000000000a',bob='00000000-0000-4000-8000-00000000000b',
  carol='00000000-0000-4000-8000-00000000000c',dave='00000000-0000-4000-8000-00000000000d';
const hash=letter=>letter.repeat(64);

test('people link only when both agree, share live, and keep what they used when access ends',
  {skip:!connectionString&&'Set AMINO_USER_FOODS_TEST_DATABASE_URL for a disposable local database'},async()=>{
    assertDisposable(connectionString);
    const db=new Client({connectionString});
    await db.connect();
    try {
      await prepare(db)
      await db.query(`
        CREATE TABLE public."User" (id uuid PRIMARY KEY, "fullName" text);
        CREATE TABLE public."ExpoPushTokens" (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "userId" uuid, key text, UNIQUE ("userId", key));
        DROP TABLE IF EXISTS auth.users; CREATE TABLE auth.users (id uuid PRIMARY KEY, email text, email_confirmed_at timestamptz);
        ALTER TABLE public."FoodItem" ADD COLUMN "partialNutrients" jsonb;
        ALTER TABLE public."Message" ADD COLUMN "operationGeneration" bigint;`)
      await db.query(read('20261015010000_profiles_push_devices_and_account_deletion.sql'))
      await db.query(read('20261015020000_people_and_sharing.sql'))
      await db.query(`insert into public."User"(id,"displayName") values ($1,'Alice'),($2,'Bob'),($3,'Carol'),($4,null)`,[alice,bob,carol,dave])
      await db.query(`insert into auth.users values ($1,'alice@example.com',now()),($2,'carol@example.com',null)`,[alice,carol])

      const one=(sql,args)=>db.query(sql,args).then(r=>r.rows[0])
      const call=(fn,...args)=>one(`select public.${fn}(${args.map((_,i)=>`$${i+1}`).join(',')}) r`,args).then(row=>row.r)
      const visible=(user,food)=>one('select public.food_visible($1,f."privateToUserId",f."lineageId") v from public."FoodItem" f where f.id=$2',[user,food]).then(r=>r.v)
      const save=(user,id,value,{ingredients=null}={})=>one('select * from public.save_user_food($1,$2,$3,$4,$5,$6)',[user,id,
        {defaultServingWeightGram:100,kcal:200,proteinG:10,carbG:20,totalFatG:5,...value},
        JSON.stringify([{name:'portion',grams:value.defaultServingWeightGram??100,amount:1}]),'[]',ingredients&&JSON.stringify(ingredients)])
      const lineage=food=>one('select "lineageId" l from public."FoodItem" where id=$1',[food]).then(r=>r.l)
      const access=user=>db.query(`select "lineageId" l,"viaShare" s,"viaRecipe" r,"viaShareAll" a from public."FoodAccess"
        where "recipientId"=$1 and "revokedAt" is null order by "lineageId"`,[user]).then(r=>r.rows)
      const log=(user,food,local)=>one('select * from public.log_food_as_meal($1,$2,$3,$4,$5)',[user,local,'2026-10-07 12:00:00','',
        {foodItemId:food,grams:100,servingId:null,servingAmount:100,loggedUnit:'g',nutrition:{kcal:321,proteinG:1}}])
      const invite=(user,letter,kind='friend',asks=false)=>call('people_create_invite',user,hash(letter),kind,asks,'link')
      const respond=(user,letter,accept,{canLog=false,shareAll=false,block=false}={})=>
        call('people_respond',user,hash(letter),null,accept,block,canLog,shareAll)

      // Linking: a name first; the invite only asks; the invitee sets their own grant.
      await assert.rejects(invite(dave,'d'),/name_required/)
      await invite(alice,'a','trainer',true)
      const preview=await call('people_invite_preview',bob,hash('a'),null)
      assert.deepEqual([preview.status,preview.kind,preview.asksToLog,preview.inviter.name],['ok','trainer',true,'Alice'])
      assert.equal((await call('people_invite_preview',alice,hash('a'),null)).status,'own')
      await assert.rejects(respond(alice,'a',true),/own_invite/)
      assert.equal((await respond(bob,'a',true,{canLog:true})).status,'accepted')
      await assert.rejects(respond(carol,'a',true),/invite_unavailable/,'an invite is used once')
      const bobsList=await call('people_list',bob)
      assert.deepEqual(bobsList.linked.map(p=>[p.name,p.kind,p.mine.canLogForMe,p.theirs.canLogForMe]),[['Alice','trainer',true,false]])
      assert.equal((await call('people_list',alice)).linked[0].kind,'client')

      // Sharing a recipe shares its private ingredients; other foods stay private.
      const rice=(await one(`insert into public."FoodItem"(name,"defaultServingWeightGram","kcalPerServing") values ('Rice',100,130) returning id`)).id
      const granola=(await save(alice,null,{name:'Granola'})).food_id
      const syrup=(await save(alice,null,{name:'Alice syrup'})).food_id
      const oats=(await save(alice,null,{name:'Oats bowl',recipePortions:2},{ingredients:[{foodItemId:syrup,grams:20},{foodItemId:rice,grams:100}]})).food_id
      const shared=await call('share_foods',alice,[await lineage(oats)],[bob,carol],true)
      assert.deepEqual(shared.refused,[{recipientId:carol,reason:'not_linked'}])
      assert.deepEqual(await access(bob),[{l:syrup,s:false,r:true,a:false},{l:oats,s:true,r:false,a:false}])
      assert.deepEqual([await visible(bob,oats),await visible(bob,syrup),await visible(bob,granola),await visible(carol,oats)],[true,true,false,false])
      assert.deepEqual(await call('food_shared_with',alice,oats),[{id:bob,name:'Bob',explicit:true,all:false,inRecipe:false}])

      // Bob logs it; Alice's next edit is a new version Bob sees, and Bob's meal keeps the version he ate.
      const bobsMeal=await log(bob,oats,'11111111-1111-4111-8111-111111111111')
      const oats2=(await save(alice,oats,{name:'Oats bowl',recipePortions:3},{ingredients:[{foodItemId:syrup,grams:30}]})).food_id
      assert.notEqual(oats2,oats)
      assert.deepEqual([await visible(bob,oats2),await visible(bob,oats)],[true,true])

      // Bob cooks with Alice's syrup, but can't pass it on to Carol.
      await invite(bob,'b')
      await respond(carol,'b',true)
      const bobsBowl=(await save(bob,null,{name:'Bob bowl',recipePortions:1},{ingredients:[{foodItemId:syrup,grams:10}]})).food_id
      const refused=await call('share_foods',bob,[await lineage(bobsBowl)],[carol],true)
      assert.equal(refused.refused[0].reason,'not_shareable')
      assert.equal(refused.refused[0].foods,'Alice syrup')
      await assert.rejects(save(alice,oats2,{name:'Oats bowl',recipePortions:3},{ingredients:[{foodItemId:bobsBowl,grams:10}]}),
        /ingredient_unavailable/,'recipes still never nest')

      // Unsharing: what Bob used becomes his own copy; his meal and recipe point at it; nutrients don't change.
      await call('share_foods',alice,[oats],[bob],false)
      assert.deepEqual(await access(bob),[])
      assert.equal(await visible(bob,oats),false)
      const copies=(await db.query(`select id,name,"copiedFromLineageId" src,"archivedAt" is not null archived from public."FoodItem"
        where "privateToUserId"=$1 and "copiedFromLineageId" is not null order by id`,[bob])).rows
      assert.deepEqual(copies.map(c=>[c.name,c.src,c.archived]).sort(),[['Alice syrup',syrup,false],['Oats bowl',oats,false],['Oats bowl',oats,true]].sort())
      const bobsRow=await one('select "foodItemId" f,kcal from public."LoggedFoodItem" where id=$1',[bobsMeal.logged_food_item_id])
      const archivedCopy=copies.find(c=>c.name==='Oats bowl'&&c.archived).id
      assert.deepEqual(bobsRow,{f:archivedCopy,kcal:321},'the meal points at a copy of the version eaten, with the same numbers')
      const syrupCopy=copies.find(c=>c.name==='Alice syrup').id
      assert.equal((await one('select "foodItemId" f from public."RecipeIngredient" where "recipeFoodItemId"=$1',[bobsBowl])).f,syrupCopy)
      assert.equal((await one(`select count(*)::int n from public."RecipeIngredient" r join public."FoodItem" f on f.id=r."recipeFoodItemId"
        where f."privateToUserId"=$1 and f.name='Oats bowl' and f."archivedAt" is null`,[bob])).n,1,'the copied recipe has its ingredient')
      // Now Bob owns everything in his bowl, so he can share it with Carol.
      assert.deepEqual((await call('share_foods',bob,[await lineage(bobsBowl)],[carol],true)).refused,[])

      // Share all: Bob's foods reach Alice, new ones too; turning it off keeps only what she used.
      await call('people_set_grant',bob,alice,null,true)
      const later=(await save(bob,null,{name:'Bob protein'})).food_id
      assert.equal(await visible(alice,later),true)
      assert.equal((await access(alice)).every(a=>a.a),true)
      await call('people_set_grant',bob,alice,null,false)
      assert.equal(await visible(alice,later),false)

      // Copy links: anyone with the link gets their own copy; nothing stays linked.
      await call('create_food_copy_link',alice,granola,hash('g'))
      assert.equal((await call('food_copy_link_preview',dave,hash('g'))).status,'ok')
      const first=await call('copy_food_from_link',dave,hash('g'),false)
      assert.equal(first.existing,false)
      assert.deepEqual(await call('copy_food_from_link',dave,hash('g'),false),{foodId:first.foodId,existing:true})
      const again=await call('copy_food_from_link',dave,hash('g'),true)
      assert.equal((await one('select name from public."FoodItem" where id=$1',[again.foodId])).name,'Granola (Alice)')
      await save(alice,granola,{name:'Granola',kcal:250})
      assert.equal((await one('select "kcalPerServing" k from public."FoodItem" where id=$1',[first.foodId])).k,200,'a copy keeps its values')
      await call('revoke_food_copy_links',alice,await lineage(granola))
      assert.equal((await call('food_copy_link_preview',dave,hash('g'))).status,'unavailable')
      await assert.rejects(call('create_food_copy_link',bob,bobsBowl,hash('h')).then(()=>
        call('create_food_copy_link',carol,bobsBowl,hash('i'))),/food_unavailable/,'only the owner makes a link')

      // Email requests reach a verified address; anything else answers the same and lists nothing.
      await call('people_request_by_email',carol,'ALICE@example.com','partner',true)
      await call('people_request_by_email',alice,'carol@example.com','friend',false)
      await call('people_request_by_email',alice,'nobody@example.com','friend',false)
      const requests=(await call('people_list',alice)).requests
      assert.deepEqual(requests.map(r=>[r.from.name,r.kind,r.asksToLog]),[['Carol','partner',true]])
      assert.deepEqual((await call('people_list',carol)).requests,[],'unverified email gets nothing')
      assert.equal((await call('people_respond',alice,null,requests[0].id,true,false,false,true)).status,'accepted')

      // Blocking ends the link and stops new invites.
      await invite(carol,'c')
      await call('people_block',alice,carol)
      assert.equal((await call('people_list',alice)).linked.some(p=>p.id===carol),false)
      assert.equal((await call('people_invite_preview',alice,hash('c'),null)).status,'unavailable')

      // Ending a link: silent, both ways.
      assert.equal(await call('people_end_link',bob,alice),true)
      assert.deepEqual((await call('people_list',alice)).linked,[])
      assert.equal((await call('share_foods',alice,[await lineage(granola)],[bob],true)).refused[0].reason,'not_linked')

      // Account deletion ends links first: people keep copies of what they used.
      await invite(alice,'e','partner')
      await respond(bob,'e',true)
      await call('share_foods',alice,[await lineage(granola)],[bob],true)
      await log(bob,granola,'22222222-2222-4222-8222-222222222222')
      await call('delete_user_data',alice)
      assert.equal((await one(`select count(*)::int n from public."FoodItem" where "privateToUserId"=$1 and name='Granola'`,[bob])).n,1)
      assert.deepEqual(await access(bob),[])
    } finally {await db.end()}
  })

test('logging for each other: only with permission, foods shared as needed, duplicates caught, labels from the server',
  {skip:!connectionString&&'Set AMINO_USER_FOODS_TEST_DATABASE_URL for a disposable local database'},async()=>{
    assertDisposable(connectionString);
    const db=new Client({connectionString});
    await db.connect();
    try {
      await prepare(db)
      await db.query(`
        CREATE TABLE public."User" (id uuid PRIMARY KEY, "fullName" text, "tzIdentifier" text);
        CREATE TABLE public."ExpoPushTokens" (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "userId" uuid, key text, UNIQUE ("userId", key));
        DROP TABLE IF EXISTS auth.users; CREATE TABLE auth.users (id uuid PRIMARY KEY, email text, email_confirmed_at timestamptz);
        ALTER TABLE public."FoodItem" ADD COLUMN "partialNutrients" jsonb;`)
      for (const file of ['20261015010000_profiles_push_devices_and_account_deletion.sql','20261015020000_people_and_sharing.sql',
        '20261015030000_log_for_others.sql','20261015060000_meals_logged_for_pages.sql']) await db.query(read(file))
      await db.query(`insert into public."User"(id,"displayName") values ($1,'Alice'),($2,'Bob'),($3,'Carol')`,[alice,bob,carol])
      const one=(sql,args)=>db.query(sql,args).then(r=>r.rows[0])
      const call=(fn,...args)=>one(`select public.${fn}(${args.map((_,i)=>`$${i+1}`).join(',')}) r`,args).then(row=>row.r)
      const save=(user,value,ingredients=null)=>one('select * from public.save_user_food($1,null,$2,$3,$4,$5)',[user,
        {defaultServingWeightGram:100,kcal:200,proteinG:10,carbG:20,totalFatG:5,...value},
        JSON.stringify([{name:'portion',grams:100,amount:1}]),'[]',ingredients&&JSON.stringify(ingredients)]).then(r=>r.food_id)
      const item=food=>({foodItemId:food,grams:150,servingId:null,servingAmount:150,loggedUnit:'g',nutrition:{kcal:300,proteinG:20}})
      const at=(user,time='2026-10-07 19:00:00')=>({userId:user,consumedOn:time})
      const logFor=(actor,targets,local,items,allow=false)=>call('log_foods_for_people',actor,JSON.stringify(targets),local,'Dinner',
        JSON.stringify(items),allow)

      // Alice and Bob are partners; Bob lets Alice log for him, not the other way round.
      await call('people_create_invite',alice,hash('a'),'partner',true,'link')
      await call('people_respond',bob,hash('a'),null,true,false,true,false)
      const chili=await save(alice,{name:'Alice chili'})
      const rice=(await one(`insert into public."FoodItem"(name,"defaultServingWeightGram","kcalPerServing") values ('Rice',100,130) returning id`)).id
      await assert.rejects(logFor(bob,[at(alice)],'10000000-0000-4000-8000-000000000001',[item(rice)]),/not_allowed/)
      await assert.rejects(logFor(alice,[at(carol)],'10000000-0000-4000-8000-000000000002',[item(rice)]),/not_allowed/)

      // Dinner for both: one meal each, Bob's labelled, Alice's chili now shared with him.
      const dinner=await logFor(alice,[at(alice),at(bob,'2026-10-07 18:00:00')],'10000000-0000-4000-8000-000000000003',[item(chili),item(rice)])
      assert.equal(dinner.status,'logged')
      const [mine,his]=dinner.meals
      const meal=id=>one('select "userId" u,"loggedByUserId" by,"loggedByName" name,"logGroupId" g,"consumedOn"::text t from public."Message" where id=$1',[id])
      assert.deepEqual(await meal(mine.messageId).then(m=>[m.u,m.by]),[alice,null])
      const bobs=await meal(his.messageId)
      assert.deepEqual([bobs.u,bobs.by,bobs.name,bobs.t],[bob,alice,'Alice','2026-10-07 18:00:00'])
      assert.equal((await one('select sum(kcal)::int k from public."LoggedFoodItem" where "messageId"=$1',[his.messageId])).k,600)
      assert.deepEqual(await one(`select reason,"revokedAt" is null live from public."FoodShare" where "recipientId"=$1`,[bob]),{reason:'log',live:true})
      // A retry is the same meals.
      const retry=await logFor(alice,[at(alice),at(bob,'2026-10-07 18:00:00')],'10000000-0000-4000-8000-000000000003',[item(chili),item(rice)])
      assert.deepEqual(retry.meals.map(m=>[m.messageId,m.created]),[[mine.messageId,false],[his.messageId,false]])

      // Bob logs the same dinner for himself later: Alice logging it again for him is caught, unless she confirms.
      const again=await logFor(alice,[at(bob,'2026-10-07 18:30:00')],'10000000-0000-4000-8000-000000000004',[item(chili)])
      assert.equal(again.status,'possible_duplicate')
      assert.equal(again.duplicates[0].meal.messageId,his.messageId)
      assert.equal((await logFor(alice,[at(bob,'2026-10-07 18:30:00')],'10000000-0000-4000-8000-000000000004',[item(chili)],true)).status,'logged')

      // Someone else's food can't be passed on through a log.
      await call('people_create_invite',carol,hash('c'),'friend',false,'link')
      await call('people_respond',alice,hash('c'),null,true,false,false,false)
      const carolsSoup=await save(carol,{name:'Carol soup'})
      await call('share_foods',carol,[carolsSoup],[alice],true)
      await assert.rejects(logFor(alice,[at(bob)],'10000000-0000-4000-8000-000000000005',[item(carolsSoup)]),/food_not_shareable/)

      // Copying a past meal, and an AI meal's copies when it resolves.
      const copied=await call('copy_meal_to_people',alice,mine.messageId,JSON.stringify([at(bob,'2026-10-08 12:00:00')]),false)
      assert.equal(copied.status,'logged')
      assert.equal((await meal(copied.meals[0].messageId)).by,alice)
      const ai=(await one(`insert into public."Message"("userId",content,status,"consumedOn","copyTo") values ($1,'chili','PROCESSING','2026-10-09 19:00:00',$2) returning id`,
        [alice,JSON.stringify([at(bob,'2026-10-09 19:00:00'),at(carol,'2026-10-09 19:00:00')])])).id
      await db.query(`insert into public."LoggedFoodItem"("userId","messageId","foodItemId",grams,kcal) values ($1,$2,$3,200,400)`,[alice,ai,chili])
      await db.query(`update public."Message" set status='RESOLVED' where id=$1`,[ai])
      const result=await one('select "copyTo" c,"copiedTo" d from public."Message" where id=$1',[ai])
      assert.equal(result.c,null)
      assert.ok(result.d.find(r=>r.userId===bob).messageId,'Bob gets his copy')
      assert.match(result.d.find(r=>r.userId===carol).error,/not_allowed/,"Carol never allowed it; Alice's meal is still resolved")

      // Only the logger may change it while allowed; the app can't forge the label.
      assert.equal(await call('meal_logged_by',alice,his.messageId),bob)
      assert.equal(await call('meal_logged_by',carol,his.messageId),null)
      assert.equal((await call('meals_logged_for',alice,bob)).length,4,'dinner, the confirmed repeat, the copied meal and the AI copy')
      // A page at a time, newest first: the cursor is the last meal of the page, and the pages cover each meal once.
      const all=await call('meals_logged_for',alice,bob)
      const first=await call('meals_logged_for',alice,bob,3)
      const rest=await call('meals_logged_for',alice,bob,3,first[2].consumedOn,first[2].id)
      assert.deepEqual([...first,...rest].map(m=>m.id),all.map(m=>m.id))
      assert.equal(rest.length,1)
      await db.query(`select set_config('request.jwt.claim.sub',$1,false)`,[bob])
      await assert.rejects(db.query(`update public."Message" set "loggedByName"='Someone' where id=$1`,[his.messageId]),/set by the server/)
      await db.query(`select set_config('request.jwt.claim.sub','',false)`)
      // Bob revokes: Alice can't log or change his meals, and the meals stay labelled.
      await call('people_set_grant',bob,alice,false,null)
      await assert.rejects(logFor(alice,[at(bob)],'10000000-0000-4000-8000-000000000006',[item(rice)]),/not_allowed/)
      assert.equal(await call('meal_logged_by',alice,his.messageId),null)
      assert.equal((await meal(his.messageId)).name,'Alice')
    } finally {await db.end()}
  })
