-- CreateEnum
CREATE TYPE "MessageStatus" AS ENUM ('RECEIVED', 'PROCESSING', 'RESOLVED', 'FAILED');

-- CreateEnum
CREATE TYPE "MessageType" AS ENUM ('CONVERSATION', 'ASSISTANT', 'FOOD_LOG_REQUEST', 'SHOW_FOOD_LOG', 'LOG_EXERCISE', 'UPDATE_USER_INFO');

-- AlterTable
ALTER TABLE "Message" ADD COLUMN     "itemsProcessed" INTEGER DEFAULT 0,
ADD COLUMN     "itemsToProcess" INTEGER DEFAULT 0,
ADD COLUMN     "messageType" "MessageType" NOT NULL DEFAULT 'CONVERSATION',
ADD COLUMN     "resolvedAt" TIMESTAMP(3),
ADD COLUMN     "status" "MessageStatus" NOT NULL DEFAULT 'RECEIVED';
