create type "public"."GenerateIconResult" as enum ('NOT_STARTED', 'STARTED', 'FAILED', 'SUCCESS');

create table "public"."IconQueue" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp without time zone not null default now(),
    "requested_food_string" text not null default ''::text,
    "started_at" timestamp without time zone,
    "finished_at" timestamp without time zone,
    "result" "GenerateIconResult" default 'NOT_STARTED'::"GenerateIconResult"
);


alter table "public"."IconQueue" enable row level security;

CREATE UNIQUE INDEX "IconQueue_pkey" ON public."IconQueue" USING btree (id);

alter table "public"."IconQueue" add constraint "IconQueue_pkey" PRIMARY KEY using index "IconQueue_pkey";


