alter table "public"."FoodImage" drop constraint "FoodImage_foodItemId_fkey";

create table "public"."FoodItemImages" (
    "id" bigint generated by default as identity not null,
    "createdAt" timestamp with time zone not null default now(),
    "foodImageId" integer,
    "foodItemId" integer,
    "downvotes" integer not null default 0
);


alter table "public"."FoodItemImages" enable row level security;

alter table "public"."FoodImage" drop column "foodItemId";

alter table "public"."FoodImage" drop column "priority";

CREATE UNIQUE INDEX "FoodItemImages_foodItemId_imageId_key" ON public."FoodItemImages" USING btree ("foodItemId", "foodImageId");

CREATE UNIQUE INDEX "FoodItemImages_pkey" ON public."FoodItemImages" USING btree (id);

alter table "public"."FoodItemImages" add constraint "FoodItemImages_pkey" PRIMARY KEY using index "FoodItemImages_pkey";

alter table "public"."FoodItemImages" add constraint "FoodItemImages_foodImageId_fkey" FOREIGN KEY ("foodImageId") REFERENCES "FoodImage"(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."FoodItemImages" validate constraint "FoodItemImages_foodImageId_fkey";

alter table "public"."FoodItemImages" add constraint "FoodItemImages_foodItemId_fkey" FOREIGN KEY ("foodItemId") REFERENCES "FoodItem"(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."FoodItemImages" validate constraint "FoodItemImages_foodItemId_fkey";

alter table "public"."FoodItemImages" add constraint "FoodItemImages_foodItemId_imageId_key" UNIQUE using index "FoodItemImages_foodItemId_imageId_key";

create policy "Enable read access for all users"
on "public"."FoodItemImages"
as permissive
for select
to public
using (true);


