-- People and sharing, phase 0 (2026-10-07, plan: 2026-10-07-people-and-sharing-plan.md): a display name for linked
-- people, push on every device, and account deletion that actually completes.

-- The name linked people see. Apple shares a name only on the first sign in, so the app asks before the first link.
ALTER TABLE public."User" ADD COLUMN IF NOT EXISTS "displayName" text;
ALTER TABLE public."User" DROP CONSTRAINT IF EXISTS "User_displayName_length";
ALTER TABLE public."User" ADD CONSTRAINT "User_displayName_length"
  CHECK ("displayName" IS NULL OR length(btrim("displayName")) BETWEEN 1 AND 40);

-- Push tokens: one row per device. The app used to delete the user's other tokens before saving its own, so only the
-- last phone got notifications; and a phone that switched accounts kept notifying the previous one. A token belongs to
-- whoever registered it last.
CREATE OR REPLACE FUNCTION public.register_push_token(p_key text) RETURNS void
LANGUAGE plpgsql SECURITY DEFINER SET search_path = '' AS $function$
BEGIN
  IF auth.uid() IS NULL OR p_key IS NULL OR length(p_key) NOT BETWEEN 10 AND 200
  THEN RAISE EXCEPTION 'Invalid push token' USING ERRCODE = '22023'; END IF;
  DELETE FROM public."ExpoPushTokens" WHERE key = p_key AND "userId" <> auth.uid();
  INSERT INTO public."ExpoPushTokens" ("userId", key) VALUES (auth.uid(), p_key) ON CONFLICT ("userId", key) DO NOTHING;
END;
$function$;
CREATE OR REPLACE FUNCTION public.unregister_push_token(p_key text) RETURNS void
LANGUAGE sql SECURITY DEFINER SET search_path = '' AS $function$
  DELETE FROM public."ExpoPushTokens" WHERE key = p_key AND "userId" = auth.uid()
$function$;
REVOKE ALL ON FUNCTION public.register_push_token(text), public.unregister_push_token(text) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.register_push_token(text), public.unregister_push_token(text) TO authenticated, service_role;

-- Notifications about people (requests, shares, meals logged for you) go through src/push/notify.ts. One row per
-- notice sent; at most one notice of a kind per person every 2 minutes, so a trainer sharing 30 recipes one by one
-- sends one push, not 30. Server only.
CREATE TABLE IF NOT EXISTS public."PushNotice" (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "userId" uuid NOT NULL REFERENCES public."User"(id) ON DELETE CASCADE,
  kind text NOT NULL,
  "sentAt" timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS "PushNotice_user_kind_idx" ON public."PushNotice"("userId", kind, "sentAt" DESC);
ALTER TABLE public."PushNotice" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public."PushNotice" FROM anon, authenticated;

-- Account deletion. The old code deleted FoodItem by "userId" (who caused a food to be created, which includes
-- shared catalogue foods) and ignored errors; meals' photos, operations and bug reports blocked deleting the meals,
-- so the auth user could not be deleted either. This removes the user's data in one transaction, in dependency
-- order. The caller then deletes the auth user, which cascades to User and its own tables.
--
-- Private foods: one that another user logged or uses in a recipe is archived and kept (orphaned, so visible to
-- nobody new), together with the private ingredients of a kept recipe; the rest are deleted.
CREATE OR REPLACE FUNCTION public.delete_user_data(p_user_id uuid) RETURNS jsonb
LANGUAGE plpgsql SET search_path = '' AS $function$
DECLARE
  meals integer[];
  logged integer[];
  kept integer[];
  gone integer[];
  simple text[][] := ARRAY[['OpenAiUsage','userId'],['SmsAuthCode','userId'],['SmsMessage','userId'],
    ['McpRequest','userId'],['WebSignIn','userId'],['UserMessageImages','userId']];
  pair text[];
BEGIN
  IF p_user_id IS NULL THEN RAISE EXCEPTION 'Invalid user' USING ERRCODE = '22023'; END IF;
  -- The meal guards (20260926000000) let this transaction delete meals the operation protocol owns.
  PERFORM pg_catalog.set_config('app.meal_operation_write', 'true', true);
  -- Links end first (20261015020000), so the people they shared with keep copies of the foods they used.
  IF pg_catalog.to_regprocedure('public.end_all_links(uuid)') IS NOT NULL THEN
    EXECUTE 'SELECT public.end_all_links($1)' USING p_user_id;
  END IF;
  SELECT coalesce(array_agg(id), '{}') INTO meals FROM public."Message" WHERE "userId" = p_user_id;
  SELECT coalesce(array_agg(id), '{}') INTO logged FROM public."LoggedFoodItem" WHERE "userId" = p_user_id;

  DELETE FROM public."userSubmittedBug" WHERE message_id = ANY(meals) OR logged_food_id = ANY(logged);
  DELETE FROM public."UserMessageImages" WHERE "messageId" = ANY(meals);
  IF pg_catalog.to_regclass('public."MealOperation"') IS NOT NULL THEN
    DELETE FROM public."MealOutbox" WHERE "operationId" IN
      (SELECT id FROM public."MealOperation" WHERE "userId" = p_user_id OR "messageId" = ANY(meals));
    DELETE FROM public."MealRevision" WHERE "userId" = p_user_id OR "messageId" = ANY(meals);
    DELETE FROM public."MealOperation" WHERE "userId" = p_user_id OR "messageId" = ANY(meals);
  END IF;
  DELETE FROM public."LoggedFoodItem" WHERE id = ANY(logged);
  DELETE FROM public."Message" WHERE id = ANY(meals);
  FOREACH pair SLICE 1 IN ARRAY simple LOOP
    IF pg_catalog.to_regclass(pg_catalog.format('public.%I', pair[1])) IS NOT NULL THEN
      EXECUTE pg_catalog.format('DELETE FROM public.%I WHERE %I = $1', pair[1], pair[2]) USING p_user_id;
    END IF;
  END LOOP;

  WITH mine AS (SELECT id FROM public."FoodItem" WHERE "privateToUserId" = p_user_id),
  used AS (
    SELECT m.id FROM mine m WHERE EXISTS (SELECT 1 FROM public."LoggedFoodItem" l WHERE l."foodItemId" = m.id)
      OR EXISTS (SELECT 1 FROM public."RecipeIngredient" r JOIN public."FoodItem" rf ON rf.id = r."recipeFoodItemId"
                 WHERE r."foodItemId" = m.id AND rf."privateToUserId" IS DISTINCT FROM p_user_id)),
  closure AS (
    SELECT id FROM used
    UNION SELECT r."foodItemId" FROM public."RecipeIngredient" r JOIN used u ON u.id = r."recipeFoodItemId"
      JOIN mine m ON m.id = r."foodItemId")
  SELECT coalesce(array_agg(id), '{}') INTO kept FROM closure;
  SELECT coalesce(array_agg(id), '{}') INTO gone FROM public."FoodItem"
    WHERE "privateToUserId" = p_user_id AND NOT (id = ANY(kept));

  UPDATE public."FoodItem" SET "archivedAt" = coalesce("archivedAt", now()), "lastUpdated" = now() WHERE id = ANY(kept);
  DELETE FROM public."RecipeIngredient" WHERE "recipeFoodItemId" = ANY(gone);
  DELETE FROM public."userSubmittedBug" WHERE food_item_id = ANY(gone);
  IF pg_catalog.to_regclass('public."FoodImage"') IS NOT NULL THEN
    DELETE FROM public."FoodImage" WHERE "foodItemId" = ANY(gone);
  END IF;
  DELETE FROM public."Serving" WHERE "foodItemId" = ANY(gone);
  DELETE FROM public."Nutrient" WHERE "foodItemId" = ANY(gone);
  DELETE FROM public."FoodItem" WHERE id = ANY(gone);

  RETURN jsonb_build_object('meals', cardinality(meals), 'loggedFoods', cardinality(logged),
    'foodsDeleted', cardinality(gone), 'foodsKept', cardinality(kept));
END;
$function$;
REVOKE ALL ON FUNCTION public.delete_user_data(uuid) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.delete_user_data(uuid) TO service_role;

NOTIFY pgrst, 'reload schema';
